#!/bin/sh
. /usr/local/etc/host-init/jail-vars.sh

for jail in ${JAILS}
do
  echo preparing $jail

  # this seems like an odd place to do this.
  # It seems only the mx-ingress gets a /etc/resolv.conf which is generated by resolvconf
  jexec $jail sysrc resolv_enable="NO"

  cp -a prepare-jails-for-ansible-helper.sh ${jailroot}/$jail/
  jexec $jail /prepare-jails-for-ansible-helper.sh
  rm ${jailroot}/$jail/prepare-jails-for-ansible-helper.sh
done
