#!/bin/sh -x

. /usr/local/etc/host-init/jail-vars.sh

exit - this needs to be rewritten to use git and checkout all three repos

# check out head if it does not already exist
if [ ! -d "${jailroot}/${INGRESS_JAIL}/var/db/freshports/ports-jail/var/db/repos/PORTS-head" ]
then
  echo directory does not exist
  echo this script needs to use the jail in the jail
  exit
  cd ${jailroot}/${INGRESS_JAIL}/var/db/freshports/ports-jail/var/db/repos
  svn co svn://svn.freebsd.org/ports/head PORTS-head
else
  echo PORTS-head already exists
fi

